"""create levels schema

Revision ID: 2b3603691cea
Revises:
Create Date: 2026-07-13 21:19:31.002915
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2b3603691cea"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercises",
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("variation_group", sa.String(length=150), nullable=False),
        sa.Column("movement_pattern", sa.String(length=50), nullable=False),
        sa.Column("equipment", sa.String(length=50), nullable=False),
        sa.Column(
            "measurement_type",
            sa.Enum(
                "load_reps",
                "bodyweight_reps",
                "duration",
                "distance",
                "rounds",
                name="measurementtype",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("compound", sa.Boolean(), nullable=False),
        sa.Column("unilateral", sa.Boolean(), nullable=False),
        sa.Column("default_rep_min", sa.Integer(), nullable=True),
        sa.Column("default_rep_max", sa.Integer(), nullable=True),
        sa.Column("default_rest_seconds", sa.Integer(), nullable=True),
        sa.Column("progression_increment_kg", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("automatic_progression_enabled", sa.Boolean(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "default_rep_max IS NULL OR default_rep_max >= default_rep_min",
            name="ck_exercises_rep_max",
        ),
        sa.CheckConstraint(
            "default_rep_min IS NULL OR default_rep_min >= 0", name="ck_exercises_rep_min"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.create_index("idx_exercises_variation_group", ["variation_group"], unique=False)

    op.create_table(
        "muscle_groups",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("body_region", sa.String(length=50), nullable=False),
        sa.Column("svg_region_ids", sa.JSON(), nullable=False),
        sa.Column("highlightable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "profiles",
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("body_weight_kg", sa.Numeric(precision=7, scale=3), nullable=True),
        sa.Column(
            "preferred_units",
            sa.Enum(
                "imperial",
                "metric",
                name="preferredunits",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("avatar_variant", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "body_weight_kg IS NULL OR body_weight_kg BETWEEN 20 AND 400",
            name="ck_profiles_body_weight_kg",
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR height_cm BETWEEN 100 AND 250", name="ck_profiles_height_cm"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "readiness_logs",
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("energy", sa.Integer(), nullable=False),
        sa.Column("soreness", sa.Integer(), nullable=False),
        sa.Column("sleep_quality", sa.Integer(), nullable=False),
        sa.Column("pain_flag", sa.Boolean(), nullable=False),
        sa.Column("note_private", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("energy BETWEEN 1 AND 5", name="ck_readiness_energy"),
        sa.CheckConstraint("sleep_quality BETWEEN 1 AND 5", name="ck_readiness_sleep"),
        sa.CheckConstraint("soreness BETWEEN 1 AND 5", name="ck_readiness_soreness"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("local_date"),
    )
    op.create_table(
        "splits",
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_seeded", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "water_logs",
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("amount_ml", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "quick_add",
                "custom",
                "correction",
                name="watersource",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint("amount_ml BETWEEN 1 AND 5000", name="ck_water_logs_amount"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("water_logs", schema=None) as batch_op:
        batch_op.create_index("idx_water_logs_local_date", ["local_date"], unique=False)

    op.create_table(
        "app_settings",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("active_split_id", sa.String(length=36), nullable=True),
        sa.Column("week_starts_on", sa.Integer(), nullable=False),
        sa.Column("default_water_goal_ml", sa.Integer(), nullable=False),
        sa.Column("water_quick_add_ml", sa.JSON(), nullable=False),
        sa.Column("primary_muscle_weight", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("secondary_muscle_weight", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("default_target_rir", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("default_load_increment_kg", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("reduced_motion_override", sa.Boolean(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("default_load_increment_kg > 0", name="ck_app_settings_load_increment"),
        sa.CheckConstraint(
            "default_target_rir BETWEEN 0 AND 10", name="ck_app_settings_target_rir"
        ),
        sa.CheckConstraint(
            "default_water_goal_ml BETWEEN 250 AND 10000", name="ck_app_settings_water_goal"
        ),
        sa.CheckConstraint(
            "primary_muscle_weight >= 0 AND secondary_muscle_weight >= 0",
            name="ck_app_settings_muscle_weights",
        ),
        sa.CheckConstraint("week_starts_on BETWEEN 0 AND 6", name="ck_app_settings_week_start"),
        sa.ForeignKeyConstraint(
            ["active_split_id"],
            ["splits.id"],
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id"),
    )
    op.create_table(
        "exercise_muscles",
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("muscle_group_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "primary",
                "secondary",
                "stabilizer",
                name="musclerole",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("contribution", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.CheckConstraint("contribution BETWEEN 0 AND 1", name="ck_exercise_muscles_contribution"),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["muscle_group_id"], ["muscle_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("exercise_id", "muscle_group_id", "role"),
    )
    with op.batch_alter_table("exercise_muscles", schema=None) as batch_op:
        batch_op.create_index("idx_exercise_muscles_exercise", ["exercise_id"], unique=False)

    op.create_table(
        "progression_suggestions",
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("suggestion_type", sa.String(length=50), nullable=False),
        sa.Column("suggested_delta", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum(
                "insufficient",
                "low",
                "medium",
                "high",
                name="suggestionconfidence",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("explanation_json", sa.JSON(), nullable=False),
        sa.Column("source_session_ids_json", sa.JSON(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(), nullable=True),
        sa.Column("dismissed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "split_days",
        sa.Column("split_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("day_type", sa.String(length=50), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("recommended_weekday", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_optional", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "recommended_weekday IS NULL OR recommended_weekday BETWEEN 0 AND 6",
            name="ck_split_days_recommended_weekday",
        ),
        sa.ForeignKeyConstraint(["split_id"], ["splits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("split_id", "sequence", name="uq_split_days_split_sequence"),
    )
    with op.batch_alter_table("split_days", schema=None) as batch_op:
        batch_op.create_index(
            "idx_split_days_split_sequence", ["split_id", "sequence"], unique=False
        )

    op.create_table(
        "visibility_settings",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("show_height", sa.Boolean(), nullable=False),
        sa.Column("show_body_weight", sa.Boolean(), nullable=False),
        sa.Column("show_water", sa.Boolean(), nullable=False),
        sa.Column("show_session_summaries", sa.Boolean(), nullable=False),
        sa.Column("show_set_details", sa.Boolean(), nullable=False),
        sa.Column("show_public_notes", sa.Boolean(), nullable=False),
        sa.Column("show_progress_charts", sa.Boolean(), nullable=False),
        sa.Column("show_personal_records", sa.Boolean(), nullable=False),
        sa.Column("show_readiness", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id"),
    )
    op.create_table(
        "workout_sessions",
        sa.Column("split_day_id", sa.String(length=36), nullable=True),
        sa.Column("session_date_local", sa.Date(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "in_progress",
                "completed",
                "cancelled",
                name="sessionstatus",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "public_visibility",
            sa.Enum(
                "private",
                "summary",
                "full",
                name="publicvisibility",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("perceived_effort", sa.Integer(), nullable=True),
        sa.Column("notes_private", sa.Text(), nullable=True),
        sa.Column("notes_public", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "perceived_effort IS NULL OR perceived_effort BETWEEN 1 AND 10",
            name="ck_workout_sessions_effort",
        ),
        sa.ForeignKeyConstraint(
            ["split_day_id"],
            ["split_days.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_workout_sessions_date_status", ["session_date_local", "status"], unique=False
        )

    op.create_table(
        "workout_template_items",
        sa.Column("split_day_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "activation",
                "power",
                "main",
                "accessory",
                "core",
                "conditioning",
                name="templateitemtype",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("rep_min", sa.Integer(), nullable=True),
        sa.Column("rep_max", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("target_rir", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("superset_group", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "rep_max IS NULL OR rep_max >= rep_min", name="ck_template_items_rep_max"
        ),
        sa.CheckConstraint("rep_min IS NULL OR rep_min >= 0", name="ck_template_items_rep_min"),
        sa.CheckConstraint("sets BETWEEN 1 AND 20", name="ck_template_items_sets"),
        sa.CheckConstraint(
            "target_rir IS NULL OR target_rir BETWEEN 0 AND 10", name="ck_template_items_target_rir"
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(["split_day_id"], ["split_days.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("split_day_id", "sequence", name="uq_template_items_day_sequence"),
    )
    with op.batch_alter_table("workout_template_items", schema=None) as batch_op:
        batch_op.create_index(
            "idx_template_items_day_sequence", ["split_day_id", "sequence"], unique=False
        )

    op.create_table(
        "session_exercises",
        sa.Column("workout_session_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("source_template_item_id", sa.String(length=36), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("display_name_snapshot", sa.String(length=200), nullable=False),
        sa.Column("variation_group_snapshot", sa.String(length=150), nullable=False),
        sa.Column("rep_min_snapshot", sa.Integer(), nullable=True),
        sa.Column("rep_max_snapshot", sa.Integer(), nullable=True),
        sa.Column("target_rir_snapshot", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("substitution_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_template_item_id"],
            ["workout_template_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workout_session_id"], ["workout_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workout_session_id", "sequence", name="uq_session_exercises_session_sequence"
        ),
    )
    with op.batch_alter_table("session_exercises", schema=None) as batch_op:
        batch_op.create_index(
            "idx_session_exercises_session_sequence",
            ["workout_session_id", "sequence"],
            unique=False,
        )

    op.create_table(
        "template_alternatives",
        sa.Column("template_item_id", sa.String(length=36), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_item_id"], ["workout_template_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("template_item_id", "exercise_id"),
    )
    op.create_table(
        "set_logs",
        sa.Column("session_exercise_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "set_type",
            sa.Enum(
                "warmup",
                "working",
                "backoff",
                "drop",
                "failure",
                name="settype",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("load_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("rir", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("rounds", sa.Integer(), nullable=True),
        sa.Column("bodyweight_assistance_kg", sa.Numeric(precision=10, scale=3), nullable=True),
        sa.Column("form_quality", sa.Integer(), nullable=True),
        sa.Column("pain_flag", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "distance_meters IS NULL OR distance_meters >= 0", name="ck_set_logs_distance"
        ),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0", name="ck_set_logs_duration"
        ),
        sa.CheckConstraint(
            "form_quality IS NULL OR form_quality BETWEEN 1 AND 5", name="ck_set_logs_form_quality"
        ),
        sa.CheckConstraint("load_kg IS NULL OR load_kg >= 0", name="ck_set_logs_load"),
        sa.CheckConstraint("reps IS NULL OR reps BETWEEN 0 AND 100", name="ck_set_logs_reps"),
        sa.CheckConstraint("rir IS NULL OR rir BETWEEN 0 AND 10", name="ck_set_logs_rir"),
        sa.CheckConstraint("rounds IS NULL OR rounds >= 0", name="ck_set_logs_rounds"),
        sa.ForeignKeyConstraint(
            ["session_exercise_id"], ["session_exercises.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint(
            "session_exercise_id", "sequence", name="uq_set_logs_exercise_sequence"
        ),
    )
    with op.batch_alter_table("set_logs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_set_logs_session_exercise_sequence",
            ["session_exercise_id", "sequence"],
            unique=False,
        )

    op.create_table(
        "achievements",
        sa.Column("achievement_type", sa.String(length=50), nullable=False),
        sa.Column("exercise_id", sa.String(length=36), nullable=True),
        sa.Column("set_log_id", sa.String(length=36), nullable=True),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("achieved_at", sa.DateTime(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["set_log_id"],
            ["set_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "personal_records",
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column(
            "record_type",
            sa.Enum(
                "max_load",
                "reps_at_load",
                "estimated_1rm",
                "session_volume",
                "duration",
                "distance",
                "rounds",
                name="recordtype",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("value_numeric", sa.Numeric(precision=16, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=32), nullable=False),
        sa.Column("reps_context", sa.Integer(), nullable=True),
        sa.Column("set_log_id", sa.String(length=36), nullable=True),
        sa.Column("achieved_at", sa.DateTime(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["set_log_id"],
            ["set_logs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("personal_records", schema=None) as batch_op:
        batch_op.create_index(
            "idx_personal_records_current",
            ["exercise_id", "record_type", "is_current"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personal_records", schema=None) as batch_op:
        batch_op.drop_index("idx_personal_records_current")

    op.drop_table("personal_records")
    op.drop_table("achievements")
    with op.batch_alter_table("set_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_set_logs_session_exercise_sequence")

    op.drop_table("set_logs")
    op.drop_table("template_alternatives")
    with op.batch_alter_table("session_exercises", schema=None) as batch_op:
        batch_op.drop_index("idx_session_exercises_session_sequence")

    op.drop_table("session_exercises")
    with op.batch_alter_table("workout_template_items", schema=None) as batch_op:
        batch_op.drop_index("idx_template_items_day_sequence")

    op.drop_table("workout_template_items")
    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.drop_index("idx_workout_sessions_date_status")

    op.drop_table("workout_sessions")
    op.drop_table("visibility_settings")
    with op.batch_alter_table("split_days", schema=None) as batch_op:
        batch_op.drop_index("idx_split_days_split_sequence")

    op.drop_table("split_days")
    op.drop_table("progression_suggestions")
    with op.batch_alter_table("exercise_muscles", schema=None) as batch_op:
        batch_op.drop_index("idx_exercise_muscles_exercise")

    op.drop_table("exercise_muscles")
    op.drop_table("app_settings")
    with op.batch_alter_table("water_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_water_logs_local_date")

    op.drop_table("water_logs")
    op.drop_table("splits")
    op.drop_table("readiness_logs")
    op.drop_table("profiles")
    op.drop_table("muscle_groups")
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.drop_index("idx_exercises_variation_group")

    op.drop_table("exercises")
    # ### end Alembic commands ###
