"""add v2 tenant schema

Revision ID: 901a70c127bb
Revises: a91f6028df36
Create Date: 2026-07-15 15:02:43.543424
"""

from collections.abc import Sequence
from datetime import UTC, datetime
import os
from uuid import NAMESPACE_URL, uuid5

from alembic import op
import sqlalchemy as sa


revision: str = "901a70c127bb"
down_revision: str | None = "a91f6028df36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

DEMO_EMAIL = "demo@levels.invalid"


def _stable_id(kind: str, key: str) -> str:
    return str(uuid5(NAMESPACE_URL, f"https://levels.app/seed/{kind}/{key}"))


def upgrade() -> None:
    connection = op.get_bind()
    tenant_tables = (
        "profiles",
        "splits",
        "workout_sessions",
        "readiness_logs",
        "water_logs",
        "personal_records",
        "achievements",
        "progression_suggestions",
    )
    populated = any(
        connection.scalar(sa.text(f"SELECT COUNT(*) FROM {table_name}"))
        for table_name in tenant_tables
    )
    bootstrap_email = os.getenv("BOOTSTRAP_OWNER_EMAIL", "").strip().lower()
    bootstrap_password_hash = os.getenv("BOOTSTRAP_OWNER_PASSWORD_HASH", "").strip()
    if populated and (not bootstrap_email or not bootstrap_password_hash):
        raise RuntimeError(
            "BOOTSTRAP_OWNER_EMAIL and BOOTSTRAP_OWNER_PASSWORD_HASH are required "
            "to migrate a populated v1 database"
        )
    if bootstrap_password_hash and not bootstrap_password_hash.startswith("$argon2"):
        raise RuntimeError("BOOTSTRAP_OWNER_PASSWORD_HASH must be an Argon2 hash")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email_normalized", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "disabled",
                name="userstatus",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "member",
                "admin",
                name="userrole",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_normalized"),
    )
    op.create_table(
        "avatar_settings",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "base_presentation",
            sa.Enum(
                "male",
                "female",
                name="basepresentation",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("skin_tone", sa.String(length=32), nullable=False),
        sa.Column("hairstyle", sa.String(length=32), nullable=False),
        sa.Column("hair_color", sa.String(length=32), nullable=False),
        sa.Column("outfit_style", sa.String(length=32), nullable=False),
        sa.Column("outfit_palette", sa.String(length=32), nullable=False),
        sa.Column("accessory", sa.String(length=32), nullable=False),
        sa.Column("background", sa.String(length=32), nullable=False),
        sa.Column("aura_style", sa.String(length=32), nullable=False),
        sa.Column("aura_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "command_receipts",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("result_resource_id", sa.String(length=36), nullable=True),
        sa.Column("result_version", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "operation", "idempotency_key", name="uq_command_receipt_actor_operation_key"
        ),
    )
    with op.batch_alter_table("command_receipts", schema=None) as batch_op:
        batch_op.create_index(
            "idx_command_receipt_actor_created", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "daily_exercise_plans",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("source_split_day_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_split_day_id"],
            ["split_days.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "local_date", name="uq_daily_exercise_plan_user_date"),
    )
    with op.batch_alter_table("daily_exercise_plans", schema=None) as batch_op:
        batch_op.create_index(
            "idx_daily_exercise_plan_user_date", ["user_id", "local_date"], unique=False
        )

    op.create_table(
        "daily_plan_overrides",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "replace",
                "swap",
                "rest",
                "skip",
                name="overrideaction",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("planned_split_day_id", sa.String(length=36), nullable=True),
        sa.Column("effective_split_day_id", sa.String(length=36), nullable=True),
        sa.Column("swap_target_local_date", sa.Date(), nullable=True),
        sa.Column(
            "schedule_effect",
            sa.Enum(
                "one_time",
                "continue_from_here",
                "swap_forward",
                "advance",
                "keep",
                name="scheduleeffect",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("swap_group_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["effective_split_day_id"],
            ["split_days.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planned_split_day_id"],
            ["split_days.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "local_date", name="uq_daily_override_user_date"),
    )
    with op.batch_alter_table("daily_plan_overrides", schema=None) as batch_op:
        batch_op.create_index(
            "idx_daily_override_user_date", ["user_id", "local_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_daily_plan_overrides_swap_group_id"), ["swap_group_id"], unique=False
        )

    op.create_table(
        "schedule_state",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("active_split_id", sa.String(length=36), nullable=True),
        sa.Column("cursor_split_day_id", sa.String(length=36), nullable=True),
        sa.Column("cursor_effective_date", sa.Date(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["active_split_id"],
            ["splits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cursor_split_day_id"],
            ["split_days.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "daily_exercise_plan_items",
        sa.Column("daily_exercise_plan_id", sa.String(length=36), nullable=False),
        sa.Column("source_template_item_id", sa.String(length=36), nullable=True),
        sa.Column("exercise_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "item_type",
            sa.Enum(
                "activation",
                "power",
                "main",
                "accessory",
                "core",
                "conditioning",
                name="templateitemtype",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("planned_sets", sa.Integer(), nullable=False),
        sa.Column("rep_min", sa.Integer(), nullable=True),
        sa.Column("rep_max", sa.Integer(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("distance_meters", sa.Numeric(precision=12, scale=3), nullable=True),
        sa.Column("rounds_target", sa.Integer(), nullable=True),
        sa.Column("rest_seconds", sa.Integer(), nullable=True),
        sa.Column("target_rir", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("superset_group", sa.String(length=50), nullable=True),
        sa.Column("optional", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["daily_exercise_plan_id"], ["daily_exercise_plans.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_template_item_id"],
            ["workout_template_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("daily_exercise_plan_id", "sequence", name="uq_daily_item_sequence"),
    )
    with op.batch_alter_table("daily_exercise_plan_items", schema=None) as batch_op:
        batch_op.create_index(
            "idx_daily_item_plan_sequence", ["daily_exercise_plan_id", "sequence"], unique=False
        )

    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_achievements_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.add_column(sa.Column("owner_user_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            "idx_exercises_owner_archived", ["owner_user_id", "archived_at"], unique=False
        )
        batch_op.create_index(
            "uq_custom_exercises_owner_slug",
            ["owner_user_id", "slug"],
            unique=True,
            sqlite_where=sa.text("owner_user_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_global_exercises_slug",
            ["slug"],
            unique=True,
            sqlite_where=sa.text("owner_user_id IS NULL"),
        )
        batch_op.create_foreign_key(
            "fk_exercises_owner_user_id_users",
            "users",
            ["owner_user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("personal_records", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.drop_index(batch_op.f("idx_personal_records_current"))
        batch_op.create_index(
            "idx_personal_records_current",
            ["user_id", "exercise_id", "record_type", "is_current"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_personal_records_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint("uq_profiles_user_id", ["user_id"])
        batch_op.create_foreign_key(
            "fk_profiles_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("progression_suggestions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(
            "fk_progression_suggestions_user_id_users",
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("readiness_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.create_index("idx_readiness_user_date", ["user_id", "local_date"], unique=False)
        batch_op.create_unique_constraint("uq_readiness_user_date", ["user_id", "local_date"])
        batch_op.create_foreign_key(
            "fk_readiness_logs_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("session_exercises", schema=None) as batch_op:
        batch_op.add_column(sa.Column("planned_sets", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "item_type",
                sa.Enum(
                    "activation",
                    "power",
                    "main",
                    "accessory",
                    "core",
                    "conditioning",
                    name="templateitemtype",
                    native_enum=False,
                    create_constraint=True,
                    length=24,
                ),
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("duration_seconds_snapshot", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("distance_meters_snapshot", sa.Numeric(precision=12, scale=3), nullable=True)
        )
        batch_op.add_column(sa.Column("rounds_target_snapshot", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("rest_seconds_snapshot", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("optional_snapshot", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("removed_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("removal_reason", sa.String(length=300), nullable=True))

    with op.batch_alter_table("workout_template_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rounds_target", sa.Integer(), nullable=True))

    with op.batch_alter_table("splits", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.create_index(
            "idx_splits_user_archived_order",
            ["user_id", "archived_at", "display_order"],
            unique=False,
        )
        batch_op.create_unique_constraint("uq_splits_user_slug", ["user_id", "slug"])
        batch_op.create_foreign_key(
            "fk_splits_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("water_logs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.drop_index(batch_op.f("idx_water_logs_local_date"))
        batch_op.create_index("idx_water_logs_local_date", ["user_id", "local_date"], unique=False)
        batch_op.create_foreign_key(
            "fk_water_logs_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("version", sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f("idx_workout_sessions_date_status"))
        batch_op.create_index(
            "idx_workout_sessions_date_status",
            ["user_id", "session_date_local", "status"],
            unique=False,
        )
        batch_op.create_foreign_key(
            "fk_workout_sessions_user_id_users", "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    unique_naming = {"uq": "uq_%(table_name)s_%(column_0_name)s"}
    with op.batch_alter_table(
        "exercises", schema=None, naming_convention=unique_naming
    ) as batch_op:
        batch_op.drop_constraint("uq_exercises_slug", type_="unique")
    with op.batch_alter_table("splits", schema=None, naming_convention=unique_naming) as batch_op:
        batch_op.drop_constraint("uq_splits_slug", type_="unique")
    with op.batch_alter_table(
        "readiness_logs", schema=None, naming_convention=unique_naming
    ) as batch_op:
        batch_op.drop_constraint("uq_readiness_logs_local_date", type_="unique")

    # The demo identity is synthetic, disabled for login, and populated further by the
    # idempotent catalog seed. Keeping its minimal profile in the migration guarantees
    # that anonymous demo reads never bind to bootstrap-member data.
    now = datetime.now(UTC)
    demo_user_id = _stable_id("user", DEMO_EMAIL)
    demo_profile_id = _stable_id("profile", demo_user_id)
    connection.execute(
        sa.text(
            """
            INSERT INTO users (
                id, email_normalized, password_hash, status, role,
                token_version, is_demo, last_login_at, created_at, updated_at
            ) VALUES (
                :id, :email, '$argon2id$demo-has-no-credentials', 'disabled', 'member',
                0, 1, NULL, :created_at, :updated_at
            )
            """
        ),
        {"id": demo_user_id, "email": DEMO_EMAIL, "created_at": now, "updated_at": now},
    )
    connection.execute(
        sa.text(
            """
            INSERT INTO profiles (
                id, user_id, display_name, height_cm, body_weight_kg, preferred_units,
                timezone, avatar_variant, created_at, updated_at
            ) VALUES (
                :id, :user_id, 'Alex Rivers', NULL, NULL, 'metric',
                'America/Toronto', 'levels-original-v2', :created_at, :updated_at
            )
            """
        ),
        {
            "id": demo_profile_id,
            "user_id": demo_user_id,
            "created_at": now,
            "updated_at": now,
        },
    )
    connection.execute(
        sa.text(
            """
            INSERT INTO visibility_settings (
                id, profile_id, show_height, show_body_weight, show_water,
                show_session_summaries, show_set_details, show_public_notes,
                show_progress_charts, show_personal_records, show_readiness
            ) VALUES (
                :id, :profile_id, 0, 0, 0, 1, 0, 0, 1, 1, 0
            )
            """
        ),
        {"id": _stable_id("visibility", demo_user_id), "profile_id": demo_profile_id},
    )
    connection.execute(
        sa.text(
            """
            INSERT INTO app_settings (
                id, profile_id, active_split_id, week_starts_on, default_water_goal_ml,
                water_quick_add_ml, primary_muscle_weight, secondary_muscle_weight,
                default_target_rir, default_load_increment_kg, reduced_motion_override,
                created_at, updated_at
            ) VALUES (
                :id, :profile_id, NULL, 1, 2800, '[250,500,750]', 1.0, 0.45,
                2.0, 1.133981, NULL, :created_at, :updated_at
            )
            """
        ),
        {
            "id": _stable_id("settings", demo_user_id),
            "profile_id": demo_profile_id,
            "created_at": now,
            "updated_at": now,
        },
    )
    connection.execute(
        sa.text(
            """
            INSERT INTO avatar_settings (
                user_id, base_presentation, skin_tone, hairstyle, hair_color,
                outfit_style, outfit_palette, accessory, background, aura_style,
                aura_enabled, created_at, updated_at
            ) VALUES (
                :user_id, 'female', 'medium_deep', 'braids', 'dark_brown',
                'training_tee', 'teal', 'headband', 'gradient', 'standard',
                1, :created_at, :updated_at
            )
            """
        ),
        {"user_id": demo_user_id, "created_at": now, "updated_at": now},
    )
    connection.execute(
        sa.text(
            """
            INSERT INTO schedule_state (
                user_id, active_split_id, cursor_split_day_id, cursor_effective_date,
                version, created_at, updated_at
            ) VALUES (
                :user_id, NULL, NULL, NULL, 0, :created_at, :updated_at
            )
            """
        ),
        {"user_id": demo_user_id, "created_at": now, "updated_at": now},
    )

    bootstrap_user_id: str | None = None
    if bootstrap_email:
        bootstrap_user_id = str(uuid5(NAMESPACE_URL, f"https://levels.app/user/{bootstrap_email}"))
        connection.execute(
            sa.text(
                """
                INSERT INTO users (
                    id, email_normalized, password_hash, status, role,
                    token_version, is_demo, last_login_at, created_at, updated_at
                ) VALUES (
                    :id, :email, :password_hash, 'active', 'member',
                    0, 0, NULL, :created_at, :updated_at
                )
                """
            ),
            {
                "id": bootstrap_user_id,
                "email": bootstrap_email,
                "password_hash": bootstrap_password_hash,
                "created_at": now,
                "updated_at": now,
            },
        )
        for table_name in tenant_tables:
            connection.execute(
                sa.text(f"UPDATE {table_name} SET user_id = :user_id WHERE user_id IS NULL"),
                {"user_id": bootstrap_user_id},
            )

        connection.execute(
            sa.text(
                """
                UPDATE session_exercises
                SET planned_sets = COALESCE(
                        (SELECT item.sets FROM workout_template_items AS item
                         WHERE item.id = session_exercises.source_template_item_id), 1
                    ),
                    item_type = COALESCE(
                        (SELECT item.item_type FROM workout_template_items AS item
                         WHERE item.id = session_exercises.source_template_item_id), 'accessory'
                    ),
                    duration_seconds_snapshot = (
                        SELECT item.duration_seconds FROM workout_template_items AS item
                        WHERE item.id = session_exercises.source_template_item_id
                    ),
                    distance_meters_snapshot = (
                        SELECT item.distance_meters FROM workout_template_items AS item
                        WHERE item.id = session_exercises.source_template_item_id
                    ),
                    rest_seconds_snapshot = (
                        SELECT item.rest_seconds FROM workout_template_items AS item
                        WHERE item.id = session_exercises.source_template_item_id
                    ),
                    optional_snapshot = COALESCE(
                        (SELECT item.optional FROM workout_template_items AS item
                         WHERE item.id = session_exercises.source_template_item_id), 0
                    )
                """
            )
        )
        connection.execute(sa.text("UPDATE workout_sessions SET version = 0 WHERE version IS NULL"))

        active_split_id = connection.scalar(
            sa.text("SELECT active_split_id FROM app_settings LIMIT 1")
        )
        cursor_split_day_id = None
        if active_split_id is not None:
            cursor_split_day_id = connection.scalar(
                sa.text(
                    """
                    SELECT id FROM split_days
                    WHERE split_id = :split_id
                    ORDER BY CASE WHEN recommended_weekday IS NULL THEN 1 ELSE 0 END,
                             recommended_weekday, sequence
                    LIMIT 1
                    """
                ),
                {"split_id": active_split_id},
            )
        connection.execute(
            sa.text(
                """
                INSERT INTO avatar_settings (
                    user_id, base_presentation, skin_tone, hairstyle, hair_color,
                    outfit_style, outfit_palette, accessory, background, aura_style,
                    aura_enabled, created_at, updated_at
                ) VALUES (
                    :user_id, 'male', 'rich', 'short_coils', 'black',
                    'training_tee', 'violet', 'none', 'gradient', 'standard',
                    1, :created_at, :updated_at
                )
                """
            ),
            {"user_id": bootstrap_user_id, "created_at": now, "updated_at": now},
        )
        connection.execute(
            sa.text(
                """
                INSERT INTO schedule_state (
                    user_id, active_split_id, cursor_split_day_id,
                    cursor_effective_date, version, created_at, updated_at
                ) VALUES (
                    :user_id, :active_split_id, :cursor_split_day_id,
                    :cursor_effective_date, 0, :created_at, :updated_at
                )
                """
            ),
            {
                "user_id": bootstrap_user_id,
                "active_split_id": active_split_id,
                "cursor_split_day_id": cursor_split_day_id,
                "cursor_effective_date": now.date(),
                "created_at": now,
                "updated_at": now,
            },
        )

    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
    with op.batch_alter_table("personal_records", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
    with op.batch_alter_table("progression_suggestions", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
    with op.batch_alter_table("readiness_logs", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
    with op.batch_alter_table("session_exercises", schema=None) as batch_op:
        batch_op.alter_column("planned_sets", existing_type=sa.Integer(), nullable=False)
        batch_op.alter_column(
            "item_type",
            existing_type=sa.Enum(
                "activation",
                "power",
                "main",
                "accessory",
                "core",
                "conditioning",
                name="templateitemtype",
                native_enum=False,
                create_constraint=True,
                length=24,
            ),
            nullable=False,
        )
        batch_op.alter_column("optional_snapshot", existing_type=sa.Boolean(), nullable=False)
    with op.batch_alter_table("splits", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
    with op.batch_alter_table("water_logs", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.String(length=36), nullable=False)
        batch_op.alter_column("version", existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    demo_user_id = _stable_id("user", DEMO_EMAIL)
    demo_profile_id = _stable_id("profile", demo_user_id)
    connection.execute(
        sa.text("DELETE FROM visibility_settings WHERE profile_id = :profile_id"),
        {"profile_id": demo_profile_id},
    )
    connection.execute(
        sa.text("DELETE FROM app_settings WHERE profile_id = :profile_id"),
        {"profile_id": demo_profile_id},
    )
    connection.execute(
        sa.text("DELETE FROM profiles WHERE user_id = :user_id"),
        {"user_id": demo_user_id},
    )
    connection.execute(sa.text("DELETE FROM users WHERE id = :user_id"), {"user_id": demo_user_id})
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workout_sessions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_workout_sessions_user_id_users", type_="foreignkey")
        batch_op.drop_index("idx_workout_sessions_date_status")
        batch_op.create_index(
            batch_op.f("idx_workout_sessions_date_status"),
            ["session_date_local", "status"],
            unique=False,
        )
        batch_op.drop_column("version")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("water_logs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_water_logs_user_id_users", type_="foreignkey")
        batch_op.drop_index("idx_water_logs_local_date")
        batch_op.create_index(batch_op.f("idx_water_logs_local_date"), ["local_date"], unique=False)
        batch_op.drop_column("user_id")

    with op.batch_alter_table("splits", schema=None) as batch_op:
        batch_op.drop_constraint("fk_splits_user_id_users", type_="foreignkey")
        batch_op.drop_constraint("uq_splits_user_slug", type_="unique")
        batch_op.drop_index("idx_splits_user_archived_order")
        batch_op.drop_column("user_id")
        batch_op.create_unique_constraint("uq_splits_slug", ["slug"])

    with op.batch_alter_table("session_exercises", schema=None) as batch_op:
        batch_op.drop_constraint("templateitemtype", type_="check")
        batch_op.drop_column("removal_reason")
        batch_op.drop_column("removed_at")
        batch_op.drop_column("optional_snapshot")
        batch_op.drop_column("rest_seconds_snapshot")
        batch_op.drop_column("rounds_target_snapshot")
        batch_op.drop_column("distance_meters_snapshot")
        batch_op.drop_column("duration_seconds_snapshot")
        batch_op.drop_column("item_type")
        batch_op.drop_column("planned_sets")

    with op.batch_alter_table("workout_template_items", schema=None) as batch_op:
        batch_op.drop_column("rounds_target")

    with op.batch_alter_table("readiness_logs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_readiness_logs_user_id_users", type_="foreignkey")
        batch_op.drop_constraint("uq_readiness_user_date", type_="unique")
        batch_op.drop_index("idx_readiness_user_date")
        batch_op.drop_column("user_id")
        batch_op.create_unique_constraint("uq_readiness_logs_local_date", ["local_date"])

    with op.batch_alter_table("progression_suggestions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_progression_suggestions_user_id_users", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_constraint("fk_profiles_user_id_users", type_="foreignkey")
        batch_op.drop_constraint("uq_profiles_user_id", type_="unique")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("personal_records", schema=None) as batch_op:
        batch_op.drop_constraint("fk_personal_records_user_id_users", type_="foreignkey")
        batch_op.drop_index("idx_personal_records_current")
        batch_op.create_index(
            batch_op.f("idx_personal_records_current"),
            ["exercise_id", "record_type", "is_current"],
            unique=False,
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.drop_constraint("fk_exercises_owner_user_id_users", type_="foreignkey")
        batch_op.drop_index(
            "uq_global_exercises_slug", sqlite_where=sa.text("owner_user_id IS NULL")
        )
        batch_op.drop_index(
            "uq_custom_exercises_owner_slug", sqlite_where=sa.text("owner_user_id IS NOT NULL")
        )
        batch_op.drop_index("idx_exercises_owner_archived")
        batch_op.drop_column("owner_user_id")
        batch_op.create_unique_constraint("uq_exercises_slug", ["slug"])

    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.drop_constraint("fk_achievements_user_id_users", type_="foreignkey")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("daily_exercise_plan_items", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_item_plan_sequence")

    op.drop_table("daily_exercise_plan_items")
    op.drop_table("schedule_state")
    with op.batch_alter_table("daily_plan_overrides", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_plan_overrides_swap_group_id"))
        batch_op.drop_index("idx_daily_override_user_date")

    op.drop_table("daily_plan_overrides")
    with op.batch_alter_table("daily_exercise_plans", schema=None) as batch_op:
        batch_op.drop_index("idx_daily_exercise_plan_user_date")

    op.drop_table("daily_exercise_plans")
    with op.batch_alter_table("command_receipts", schema=None) as batch_op:
        batch_op.drop_index("idx_command_receipt_actor_created")

    op.drop_table("command_receipts")
    op.drop_table("avatar_settings")
    op.drop_table("users")
    # ### end Alembic commands ###
