/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDemoBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMyAvatar"];
        trace?: never;
    };
    "/me/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyStreak"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today/override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putTodayOverride"];
        post?: never;
        delete: operations["deleteTodayOverride"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["skipToday"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["replaceTodayExercisePlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAvailableExercises"];
        put?: never;
        post: operations["createExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/muscles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMuscleGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        get: operations["getExercise"];
        put?: never;
        post?: never;
        delete: operations["archiveExercise"];
        options?: never;
        head?: never;
        patch: operations["updateExercise"];
        trace?: never;
    };
    "/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSplits"];
        put?: never;
        post: operations["createSplit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/splits/{split_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        get: operations["getSplit"];
        put?: never;
        post?: never;
        delete: operations["archiveSplit"];
        options?: never;
        head?: never;
        patch: operations["updateSplit"];
        trace?: never;
    };
    "/splits/{split_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateSplit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/sessions/{session_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addOrSubstituteSessionExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/exercises/{session_exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
                session_exercise_id: components["parameters"]["SessionExerciseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["removeSessionExercise"];
        options?: never;
        head?: never;
        patch: operations["updateSessionExercise"];
        trace?: never;
    };
    "/sessions/{session_id}/exercises/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reorderSessionExercises"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSet"];
        options?: never;
        head?: never;
        patch: operations["updateSet"];
        trace?: never;
    };
    "/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/water/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWaterToday"];
        put?: never;
        post: operations["addWater"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/water/today/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["undoWater"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/growth/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGrowthSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** @enum {string} */
            database?: "ok" | "degraded";
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                field_errors?: {
                    [key: string]: string;
                };
                current_version?: number;
                request_id?: string;
            };
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
            /** @default America/Toronto */
            timezone: string;
            /**
             * @default metric
             * @enum {string}
             */
            preferred_units: "metric" | "imperial";
        };
        LoginRequestV2: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            expires_in: number;
            user: components["schemas"]["CurrentUser"];
        };
        CurrentUser: {
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @enum {string} */
            role: "member" | "admin";
            /** @enum {string} */
            readonly account_status: "active" | "disabled";
            timezone: string;
            /** @enum {string} */
            preferred_units: "metric" | "imperial";
        };
        PublicProfile: {
            display_name: string;
            height_cm?: number | null;
            body_weight_kg?: number | null;
            /** @enum {string} */
            preferred_units: "imperial" | "metric";
            timezone: string;
        };
        Profile: {
            id: string;
            display_name: string;
            height_cm?: number | null;
            body_weight_kg?: number | null;
            /** @enum {string} */
            preferred_units: "imperial" | "metric";
            timezone: string;
        };
        AvatarSettings: {
            /** @enum {string} */
            base_presentation: "male" | "female";
            /** @enum {string} */
            skin_tone: "deep" | "rich" | "medium_deep" | "medium" | "light_medium" | "light";
            /** @enum {string} */
            hairstyle: "short_coils" | "fade" | "waves" | "short_locs" | "locs" | "braids" | "long_curls" | "curly_bob" | "bun" | "bob" | "short_straight" | "covered" | "bald";
            /** @enum {string} */
            hair_color: "black" | "dark_brown" | "brown" | "auburn" | "gray" | "blonde";
            /** @enum {string} */
            outfit_style: "training_tee" | "tank_and_shorts" | "long_sleeve" | "modest_activewear";
            /** @enum {string} */
            outfit_palette: "violet" | "teal" | "blue" | "rose" | "neutral";
            /** @enum {string} */
            accessory: "none" | "glasses" | "headband" | "wristbands" | "cap";
            /** @enum {string} */
            background: "none" | "gradient" | "gym" | "dusk";
            /** @enum {string} */
            aura_style: "standard" | "rings" | "sparks";
            aura_enabled: boolean;
        };
        AvatarSettingsUpdate: {
            /** @enum {string} */
            base_presentation?: "male" | "female";
            /** @enum {string} */
            skin_tone?: "deep" | "rich" | "medium_deep" | "medium" | "light_medium" | "light";
            /** @enum {string} */
            hairstyle?: "short_coils" | "fade" | "waves" | "short_locs" | "locs" | "braids" | "long_curls" | "curly_bob" | "bun" | "bob" | "short_straight" | "covered" | "bald";
            /** @enum {string} */
            hair_color?: "black" | "dark_brown" | "brown" | "auburn" | "gray" | "blonde";
            /** @enum {string} */
            outfit_style?: "training_tee" | "tank_and_shorts" | "long_sleeve" | "modest_activewear";
            /** @enum {string} */
            outfit_palette?: "violet" | "teal" | "blue" | "rose" | "neutral";
            /** @enum {string} */
            accessory?: "none" | "glasses" | "headband" | "wristbands" | "cap";
            /** @enum {string} */
            background?: "none" | "gradient" | "gym" | "dusk";
            /** @enum {string} */
            aura_style?: "standard" | "rings" | "sparks";
            aura_enabled?: boolean;
        };
        StreakSummary: {
            current_count: number;
            longest_count: number;
            /** @enum {string} */
            tier: "none" | "subtle" | "active" | "energized" | "legendary";
            /** Format: date */
            last_qualified_local_date: string | null;
            next_milestone: number | null;
        };
        ProfileUpdate: {
            display_name?: string;
            height_cm?: number | null;
            body_weight_kg?: number | null;
            /** @enum {string} */
            preferred_units?: "imperial" | "metric";
            timezone?: string;
        };
        Visibility: {
            show_height?: boolean;
            show_body_weight?: boolean;
            show_water?: boolean;
            show_session_summaries?: boolean;
            show_set_details?: boolean;
            show_public_notes?: boolean;
            show_progress_charts?: boolean;
            show_personal_records?: boolean;
            show_readiness?: boolean;
        };
        Settings: {
            active_split_id?: string | null;
            week_starts_on: number;
            default_water_goal_ml: number;
            water_quick_add_ml: number[];
            default_target_rir?: number;
            default_load_increment_kg?: number;
            reduced_motion_override: boolean | null;
            visibility: components["schemas"]["Visibility"];
        };
        SettingsUpdate: {
            active_split_id?: string | null;
            week_starts_on?: number;
            default_water_goal_ml?: number;
            water_quick_add_ml?: number[];
            default_target_rir?: number;
            default_load_increment_kg?: number;
            reduced_motion_override?: boolean | null;
            visibility?: components["schemas"]["Visibility"];
        };
        MuscleGroup: {
            id: string;
            slug: string;
            display_name: string;
            body_region: string;
            svg_region_ids: string[];
            highlightable: boolean;
        };
        MuscleTarget: {
            slug: string;
            display_name: string;
            /** @enum {string} */
            role: "primary" | "secondary" | "stabilizer";
            intensity: number;
            svg_region_ids: string[];
        };
        Exercise: {
            id: string;
            /** @enum {string} */
            scope: "global" | "custom";
            can_edit: boolean;
            slug: string;
            name: string;
            aliases: string[];
            variation_group: string;
            movement_pattern: string;
            equipment: string;
            /** @enum {string} */
            measurement_type: "load_reps" | "bodyweight_reps" | "duration" | "distance" | "rounds";
            compound: boolean;
            unilateral: boolean;
            default_rep_min?: number | null;
            default_rep_max?: number | null;
            default_rest_seconds?: number | null;
            automatic_progression_enabled: boolean;
            muscle_targets: components["schemas"]["MuscleTarget"][];
        };
        MuscleTargetInput: {
            slug: string;
            /** @enum {string} */
            role: "primary" | "secondary" | "stabilizer";
            intensity: number;
        };
        ExerciseWrite: {
            name: string;
            slug: string;
            aliases?: string[];
            variation_group: string;
            movement_pattern: string;
            equipment: string;
            /** @enum {string} */
            measurement_type: "load_reps" | "bodyweight_reps" | "duration" | "distance" | "rounds";
            compound?: boolean;
            unilateral?: boolean;
            default_rep_min?: number | null;
            default_rep_max?: number | null;
            default_rest_seconds?: number | null;
            automatic_progression_enabled?: boolean;
            muscle_targets: components["schemas"]["MuscleTargetInput"][];
        };
        TemplateItem: {
            id: string;
            exercise: components["schemas"]["Exercise"];
            sequence: number;
            /** @enum {string} */
            item_type: "activation" | "power" | "main" | "accessory" | "core" | "conditioning";
            sets: number;
            rep_min?: number | null;
            rep_max?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds_target?: number | null;
            rest_seconds?: number | null;
            target_rir?: number | null;
            superset_group?: string | null;
            notes?: string | null;
            optional: boolean;
            alternatives?: components["schemas"]["Exercise"][];
        };
        SplitDay: {
            id: string;
            name: string;
            day_type: string;
            sequence: number;
            is_optional: boolean;
            items: components["schemas"]["TemplateItem"][];
        };
        Split: {
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            is_active: boolean;
            days: components["schemas"]["SplitDay"][];
        };
        SplitWrite: {
            name: string;
            slug?: string;
            description?: string | null;
            days?: {
                id?: string | null;
                name: string;
                day_type: string;
                sequence: number;
                is_optional: boolean;
                items: {
                    id?: string | null;
                    exercise_id: string;
                    sequence: number;
                    item_type: string;
                    sets: number;
                    rep_min?: number | null;
                    rep_max?: number | null;
                    duration_seconds?: number | null;
                    distance_meters?: number | null;
                    rounds_target?: number | null;
                    rest_seconds?: number | null;
                    target_rir?: number | null;
                    optional?: boolean;
                    alternative_exercise_ids?: string[];
                }[];
            }[];
        };
        ExerciseList: components["schemas"]["Exercise"][];
        DailyPlanOverride: {
            id: string;
            /** Format: date */
            local_date: string;
            /** @enum {string} */
            action: "replace" | "swap" | "rest" | "skip";
            planned_split_day_id?: string | null;
            effective_split_day_id?: string | null;
            /** Format: date */
            swap_target_local_date?: string | null;
            /** @enum {string} */
            schedule_effect: "one_time" | "continue_from_here" | "swap_forward" | "advance" | "keep";
            reason?: string | null;
            version: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ExercisePlanItemInput: {
            source_template_item_id?: string | null;
            exercise_id: string;
            sequence: number;
            /**
             * @default accessory
             * @enum {string}
             */
            item_type: "activation" | "power" | "main" | "accessory" | "core" | "conditioning";
            planned_sets: number;
            rep_min?: number | null;
            rep_max?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds_target?: number | null;
            rest_seconds?: number | null;
            target_rir?: number | null;
            superset_group?: string | null;
            /** @default false */
            optional: boolean;
            notes?: string | null;
        };
        ExercisePlanItem: {
            id: string;
            source_template_item_id?: string | null;
            exercise: components["schemas"]["Exercise"];
            sequence: number;
            /** @enum {string} */
            item_type: "activation" | "power" | "main" | "accessory" | "core" | "conditioning";
            planned_sets: number;
            rep_min?: number | null;
            rep_max?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds_target?: number | null;
            rest_seconds?: number | null;
            target_rir?: number | null;
            superset_group?: string | null;
            optional: boolean;
            notes?: string | null;
        };
        TodayOverrideRequest: {
            /** Format: date */
            local_date: string;
            /** @constant */
            action: "replace";
            effective_split_day_id: string;
            /** @enum {string} */
            schedule_effect: "one_time" | "continue_from_here";
            reason?: string | null;
            expected_version: number;
        } | {
            /** Format: date */
            local_date: string;
            /** @constant */
            action: "swap";
            effective_split_day_id: string;
            /** Format: date */
            swap_target_local_date: string;
            /** @constant */
            schedule_effect: "swap_forward";
            reason?: string | null;
            expected_version: number;
        } | {
            /** Format: date */
            local_date: string;
            /** @constant */
            action: "rest";
            /** @constant */
            schedule_effect: "one_time";
            reason?: string | null;
            expected_version: number;
        };
        SkipTodayRequest: {
            /** Format: date */
            local_date: string;
            /** @enum {string} */
            schedule_effect: "advance" | "keep";
            reason?: string | null;
            expected_version: number;
        };
        TodayExercisePlanUpdate: {
            /** Format: date */
            local_date: string;
            source_split_day_id?: string | null;
            items: components["schemas"]["ExercisePlanItemInput"][];
            /**
             * @default today_only
             * @enum {string}
             */
            scope: "today_only" | "save_to_split";
            expected_version: number;
        } & unknown;
        TodayV2: {
            /** Format: date */
            local_date: string;
            user: components["schemas"]["CurrentUser"];
            planned_day: components["schemas"]["SplitDay"] | null;
            effective_day: components["schemas"]["SplitDay"] | null;
            override: components["schemas"]["DailyPlanOverride"] | null;
            schedule_version: number;
            exercise_plan: components["schemas"]["ExercisePlanItem"][];
            active_session: components["schemas"]["WorkoutSession"] | null;
            muscle_targets: components["schemas"]["MuscleTarget"][];
            water: components["schemas"]["WaterDay"];
            latest_achievements: components["schemas"]["Achievement"][];
            avatar: components["schemas"]["AvatarSettings"];
            streak: components["schemas"]["StreakSummary"];
        };
        DemoToday: {
            /** Format: date */
            local_date: string;
            profile: components["schemas"]["PublicProfile"];
            effective_day: components["schemas"]["SplitDay"] | null;
            exercise_plan: components["schemas"]["ExercisePlanItem"][];
            muscle_targets: components["schemas"]["MuscleTarget"][];
            avatar: components["schemas"]["AvatarSettings"];
            streak: components["schemas"]["StreakSummary"];
        };
        DemoJournalSample: {
            id: string;
            /** Format: date */
            session_date_local: string;
            title: string;
            /** Format: date-time */
            completed_at: string;
            exercises_completed: number;
        };
        DemoProgressSummary: {
            completed_sessions: number;
            current_records: components["schemas"]["PersonalRecord"][];
        };
        DemoBootstrap: {
            /** @constant */
            mode: "demo";
            profile: components["schemas"]["PublicProfile"];
            today: components["schemas"]["DemoToday"];
            avatar: components["schemas"]["AvatarSettings"];
            splits: components["schemas"]["Split"][];
            exercises: components["schemas"]["ExerciseList"];
            journal_samples: components["schemas"]["DemoJournalSample"][];
            progress: components["schemas"]["DemoProgressSummary"];
            streak: components["schemas"]["StreakSummary"];
        };
        SetLog: {
            id: string;
            sequence: number;
            /** @enum {string} */
            set_type: "warmup" | "working" | "backoff" | "drop" | "failure";
            load_kg?: number | null;
            reps?: number | null;
            rir?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds?: number | null;
            form_quality?: number | null;
            pain_flag: boolean;
            /** Format: date-time */
            completed_at: string;
            notes?: string | null;
        };
        SessionExercise: {
            id: string;
            exercise_id: string;
            source_template_item_id?: string | null;
            display_name: string;
            variation_group: string;
            sequence: number;
            planned_sets: number;
            /** @enum {string} */
            item_type: "activation" | "power" | "main" | "accessory" | "core" | "conditioning";
            rep_min?: number | null;
            rep_max?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds_target?: number | null;
            rest_seconds?: number | null;
            target_rir?: number | null;
            optional: boolean;
            notes?: string | null;
            substitution_reason?: string | null;
            /** Format: date-time */
            removed_at?: string | null;
            removal_reason?: string | null;
            sets: components["schemas"]["SetLog"][];
        };
        WorkoutSession: {
            id: string;
            version: number;
            split_day_id?: string | null;
            /** Format: date */
            session_date_local: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            /** @enum {string} */
            status: "draft" | "in_progress" | "completed" | "cancelled";
            title: string;
            perceived_effort?: number | null;
            notes_private?: string | null;
            exercises: components["schemas"]["SessionExercise"][];
        };
        StartSession: {
            expected_schedule_version: number;
            split_day_id?: string | null;
            title?: string | null;
            /** Format: date */
            date?: string | null;
        };
        SessionUpdate: {
            /** @enum {string} */
            status?: "in_progress" | "completed" | "cancelled";
            title?: string;
            perceived_effort?: number | null;
            notes_private?: string | null;
        };
        AddSessionExercise: {
            exercise_id: string;
            expected_version: number;
            replace_session_exercise_id?: string | null;
            substitution_reason?: string | null;
            sequence?: number | null;
        };
        SessionExerciseUpdate: {
            expected_version: number;
            exercise_id?: string;
            planned_sets?: number;
            /** @enum {string} */
            item_type?: "activation" | "power" | "main" | "accessory" | "core" | "conditioning";
            rep_min?: number | null;
            rep_max?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds_target?: number | null;
            rest_seconds?: number | null;
            target_rir?: number | null;
            optional?: boolean;
            notes?: string | null;
            substitution_reason?: string | null;
        };
        ReorderSessionExercises: {
            expected_version: number;
            ordered_session_exercise_ids: string[];
        };
        SetWrite: {
            session_exercise_id: string;
            sequence?: number | null;
            /** @enum {string} */
            set_type: "warmup" | "working" | "backoff" | "drop" | "failure";
            load_kg?: number | null;
            reps?: number | null;
            rir?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds?: number | null;
            bodyweight_assistance_kg?: number | null;
            form_quality?: number | null;
            /** @default false */
            pain_flag: boolean;
            notes?: string | null;
        };
        SetWriteResponse: {
            set: components["schemas"]["SetLog"];
            new_achievements: components["schemas"]["Achievement"][];
            affected_records: components["schemas"]["PersonalRecord"][];
        };
        Achievement: {
            id: string;
            achievement_type: string;
            exercise_id?: string | null;
            title: string;
            message: string;
            /** Format: date-time */
            achieved_at: string;
            public: boolean;
        };
        PersonalRecord: {
            id: string;
            exercise_id: string;
            exercise_name?: string;
            /** @enum {string} */
            record_type: "max_load" | "reps_at_load" | "estimated_1rm" | "session_volume" | "duration" | "distance" | "rounds";
            value_numeric: number;
            unit: string;
            reps_context?: number | null;
            /** Format: date-time */
            achieved_at: string;
        };
        WaterWrite: {
            amount_ml: number;
            /** Format: date-time */
            occurred_at?: string | null;
            /**
             * @default custom
             * @enum {string}
             */
            source: "quick_add" | "custom";
            note?: string | null;
        };
        WaterDay: {
            /** Format: date */
            local_date: string;
            total_ml: number;
            goal_ml: number;
            progress_ratio: number;
            entries: {
                id: string;
                amount_ml: number;
                /** Format: date-time */
                occurred_at: string;
            }[];
        };
        GrowthSuggestion: {
            exercise_id: string;
            exercise_name: string;
            /** @enum {string} */
            suggestion_type: "insufficient_data" | "increase_load" | "add_rep" | "repeat_load" | "maintain" | "reduce_volume" | "easier_variation" | "no_progression";
            suggested_delta?: number | null;
            delta_unit?: string | null;
            /** @enum {string} */
            confidence: "insufficient" | "low" | "medium" | "high";
            explanation: string[];
            source_session_ids: string[];
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated actor is not allowed to perform this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request conflicts with current state or optimistic-concurrency version. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Semantically invalid request. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limited. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        LocalDate: string;
        LocalDateRequired: string;
        ExerciseId: string;
        SplitId: string;
        SessionId: string;
        SessionExerciseId: string;
        SetId: string;
        IdempotencyKey: string;
        IdempotencyKeyRequired: string;
        ExpectedVersion: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy service. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestV2"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created and authenticated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current authenticated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local authentication state may be cleared. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getDemoBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fictional read-only demo data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoBootstrap"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMyAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's avatar appearance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvatarSettingsUpdate"];
            };
        };
        responses: {
            /** @description Updated avatar appearance. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvatarSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    getMyStreak: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user's schedule-aware streak. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getToday: {
        parameters: {
            query?: {
                date?: components["parameters"]["LocalDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Planned and effective workout for the requested local date. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayV2"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationError"];
        };
    };
    putTodayOverride: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodayOverrideRequest"];
            };
        };
        responses: {
            /** @description Updated effective plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayV2"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteTodayOverride: {
        parameters: {
            query: {
                local_date: components["parameters"]["LocalDateRequired"];
                expected_version: components["parameters"]["ExpectedVersion"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Override removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    skipToday: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipTodayRequest"];
            };
        };
        responses: {
            /** @description Today skipped and schedule updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayV2"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    replaceTodayExercisePlan: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodayExercisePlanUpdate"];
            };
        };
        responses: {
            /** @description Updated effective exercise plan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayV2"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listAvailableExercises: {
        parameters: {
            query?: {
                scope?: "available" | "global" | "mine";
                search?: string;
                muscle_id?: string;
                movement_pattern?: string;
                equipment?: string;
                measurement_type?: "load_reps" | "bodyweight_reps" | "duration" | "distance" | "rounds";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseWrite"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listMuscleGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shared read-only muscle catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MuscleGroup"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseWrite"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    listSplits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Splits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSplit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitWrite"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Split. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitWrite"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    activateSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activated split. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                exercise_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions, filtered by visibility. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSession"];
            };
        };
        responses: {
            /** @description Started session. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session, filtered by visibility. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    addOrSubstituteSessionExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSessionExercise"];
            };
        };
        responses: {
            /** @description Added/substituted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionExercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    removeSessionExercise: {
        parameters: {
            query: {
                expected_version: components["parameters"]["ExpectedVersion"];
                confirm_logged_sets?: boolean;
            };
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
                session_exercise_id: components["parameters"]["SessionExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise soft-removed from the active session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSessionExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
                session_exercise_id: components["parameters"]["SessionExerciseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionExerciseUpdate"];
            };
        };
        responses: {
            /** @description Updated active-session exercise snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    reorderSessionExercises: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderSessionExercises"];
            };
        };
        responses: {
            /** @description Reordered active-session exercises. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    createSet: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWrite"];
            };
        };
        responses: {
            /** @description Set and record result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetWriteResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    deleteSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted and records rebuilt. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWrite"];
            };
        };
        responses: {
            /** @description Updated set and affected records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetWriteResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    completeSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKeyRequired"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getWaterToday: {
        parameters: {
            query?: {
                date?: components["parameters"]["LocalDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible daily hydration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterDay"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addWater: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaterWrite"];
            };
        };
        responses: {
            /** @description Added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterDay"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    undoWater: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest entry removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterDay"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
        };
    };
    listRecords: {
        parameters: {
            query?: {
                exercise_id?: string;
                current_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalRecord"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getGrowthSuggestions: {
        parameters: {
            query?: {
                date?: components["parameters"]["LocalDate"];
                split_day_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Explainable suggestions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthSuggestion"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    exportData: {
        parameters: {
            query: {
                format: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
