/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExercises"];
        put?: never;
        post: operations["createExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exercises/{exercise_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        get: operations["getExercise"];
        put?: never;
        post?: never;
        delete: operations["archiveExercise"];
        options?: never;
        head?: never;
        patch: operations["updateExercise"];
        trace?: never;
    };
    "/splits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSplits"];
        put?: never;
        post: operations["createSplit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/splits/{split_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        get: operations["getSplit"];
        put?: never;
        post?: never;
        delete: operations["archiveSplit"];
        options?: never;
        head?: never;
        patch: operations["updateSplit"];
        trace?: never;
    };
    "/splits/{split_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["activateSplit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSessions"];
        put?: never;
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        get: operations["getSession"];
        put?: never;
        post?: never;
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch: operations["updateSession"];
        trace?: never;
    };
    "/sessions/{session_id}/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addOrSubstituteSessionExercise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteSet"];
        options?: never;
        head?: never;
        patch: operations["updateSet"];
        trace?: never;
    };
    "/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/water/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWaterToday"];
        put?: never;
        post: operations["addWater"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/water/today/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["undoWater"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRecords"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/growth/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGrowthSuggestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["exportData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            version: string;
            /** @enum {string} */
            database?: "ok" | "degraded";
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
                field_errors?: {
                    [key: string]: string;
                };
                request_id?: string;
            };
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            access_token: string;
            expires_in_seconds: number;
            admin: {
                display_name: string;
            };
        };
        PublicProfile: {
            display_name: string;
            height_cm?: number | null;
            body_weight_kg?: number | null;
            /** @enum {string} */
            preferred_units: "imperial" | "metric";
            timezone: string;
            avatar_variant: string;
        };
        AdminProfile: components["schemas"]["PublicProfile"] & {
            id: string;
        };
        ProfileUpdate: {
            display_name?: string;
            height_cm?: number | null;
            body_weight_kg?: number | null;
            /** @enum {string} */
            preferred_units?: "imperial" | "metric";
            timezone?: string;
        };
        Visibility: {
            show_height?: boolean;
            show_body_weight?: boolean;
            show_water?: boolean;
            show_session_summaries?: boolean;
            show_set_details?: boolean;
            show_public_notes?: boolean;
            show_progress_charts?: boolean;
            show_personal_records?: boolean;
            show_readiness?: boolean;
        };
        Settings: {
            active_split_id?: string | null;
            default_water_goal_ml: number;
            water_quick_add_ml: number[];
            default_target_rir?: number;
            default_load_increment_kg?: number;
            visibility: components["schemas"]["Visibility"];
        };
        SettingsUpdate: {
            active_split_id?: string | null;
            default_water_goal_ml?: number;
            water_quick_add_ml?: number[];
            default_target_rir?: number;
            default_load_increment_kg?: number;
            visibility?: components["schemas"]["Visibility"];
        };
        MuscleTarget: {
            slug: string;
            display_name: string;
            /** @enum {string} */
            role: "primary" | "secondary" | "stabilizer";
            intensity: number;
            svg_region_ids: string[];
        };
        Exercise: {
            id: string;
            slug: string;
            name: string;
            aliases: string[];
            variation_group: string;
            movement_pattern: string;
            equipment: string;
            /** @enum {string} */
            measurement_type: "load_reps" | "bodyweight_reps" | "duration" | "distance" | "rounds";
            compound: boolean;
            unilateral: boolean;
            default_rep_min?: number | null;
            default_rep_max?: number | null;
            default_rest_seconds?: number | null;
            automatic_progression_enabled: boolean;
            muscle_targets: components["schemas"]["MuscleTarget"][];
        };
        ExerciseWrite: {
            name: string;
            slug: string;
            aliases?: string[];
            variation_group: string;
            movement_pattern: string;
            equipment: string;
            /** @enum {string} */
            measurement_type: "load_reps" | "bodyweight_reps" | "duration" | "distance" | "rounds";
            compound?: boolean;
            unilateral?: boolean;
            default_rep_min?: number | null;
            default_rep_max?: number | null;
            default_rest_seconds?: number | null;
            automatic_progression_enabled?: boolean;
            muscle_targets: components["schemas"]["MuscleTarget"][];
        };
        TemplateItem: {
            id: string;
            exercise: components["schemas"]["Exercise"];
            sequence: number;
            /** @enum {string} */
            item_type: "activation" | "power" | "main" | "accessory" | "core" | "conditioning";
            sets: number;
            rep_min?: number | null;
            rep_max?: number | null;
            rest_seconds?: number | null;
            target_rir?: number | null;
            superset_group?: string | null;
            notes?: string | null;
            optional: boolean;
            alternatives?: components["schemas"]["Exercise"][];
        };
        SplitDay: {
            id: string;
            name: string;
            day_type: string;
            sequence: number;
            is_optional: boolean;
            items: components["schemas"]["TemplateItem"][];
        };
        Split: {
            id: string;
            name: string;
            slug: string;
            description?: string | null;
            is_active: boolean;
            days: components["schemas"]["SplitDay"][];
        };
        SplitWrite: {
            name: string;
            slug?: string;
            description?: string | null;
            days?: {
                id?: string | null;
                name: string;
                day_type: string;
                sequence: number;
                is_optional: boolean;
                items: {
                    id?: string | null;
                    exercise_id: string;
                    sequence: number;
                    item_type: string;
                    sets: number;
                    rep_min?: number | null;
                    rep_max?: number | null;
                    rest_seconds?: number | null;
                    target_rir?: number | null;
                    optional?: boolean;
                    alternative_exercise_ids?: string[];
                }[];
            }[];
        };
        SetLog: {
            id: string;
            sequence: number;
            /** @enum {string} */
            set_type: "warmup" | "working" | "backoff" | "drop" | "failure";
            load_kg?: number | null;
            reps?: number | null;
            rir?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds?: number | null;
            form_quality?: number | null;
            pain_flag: boolean;
            /** Format: date-time */
            completed_at: string;
            notes?: string | null;
        };
        SessionExercise: {
            id: string;
            exercise_id: string;
            display_name: string;
            variation_group?: string;
            sequence: number;
            rep_min?: number | null;
            rep_max?: number | null;
            target_rir?: number | null;
            substitution_reason?: string | null;
            sets: components["schemas"]["SetLog"][];
        };
        WorkoutSession: {
            id: string;
            split_day_id?: string | null;
            /** Format: date */
            session_date_local: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            completed_at?: string | null;
            /** @enum {string} */
            status: "draft" | "in_progress" | "completed" | "cancelled";
            title: string;
            /** @enum {string} */
            public_visibility: "private" | "summary" | "full";
            perceived_effort?: number | null;
            notes_public?: string | null;
            notes_private?: string | null;
            exercises: components["schemas"]["SessionExercise"][];
        };
        StartSession: {
            split_day_id?: string | null;
            title?: string | null;
            /** Format: date */
            date?: string | null;
        } | unknown | unknown;
        SessionUpdate: {
            /** @enum {string} */
            status?: "in_progress" | "completed" | "cancelled";
            title?: string;
            /** @enum {string} */
            public_visibility?: "private" | "summary" | "full";
            perceived_effort?: number | null;
            notes_private?: string | null;
            notes_public?: string | null;
        };
        AddSessionExercise: {
            exercise_id: string;
            replace_session_exercise_id?: string | null;
            substitution_reason?: string | null;
            sequence?: number | null;
        };
        SetWrite: {
            session_exercise_id: string;
            sequence?: number | null;
            /** @enum {string} */
            set_type: "warmup" | "working" | "backoff" | "drop" | "failure";
            load_kg?: number | null;
            reps?: number | null;
            rir?: number | null;
            duration_seconds?: number | null;
            distance_meters?: number | null;
            rounds?: number | null;
            bodyweight_assistance_kg?: number | null;
            form_quality?: number | null;
            /** @default false */
            pain_flag: boolean;
            notes?: string | null;
        };
        SetWriteResponse: {
            set: components["schemas"]["SetLog"];
            new_achievements: components["schemas"]["Achievement"][];
            affected_records: components["schemas"]["PersonalRecord"][];
        };
        Achievement: {
            id: string;
            achievement_type: string;
            exercise_id?: string | null;
            title: string;
            message: string;
            /** Format: date-time */
            achieved_at: string;
            public: boolean;
        };
        PersonalRecord: {
            id: string;
            exercise_id: string;
            exercise_name?: string;
            /** @enum {string} */
            record_type: "max_load" | "reps_at_load" | "estimated_1rm" | "session_volume" | "duration" | "distance" | "rounds";
            value_numeric: number;
            unit: string;
            reps_context?: number | null;
            /** Format: date-time */
            achieved_at: string;
        };
        WaterWrite: {
            amount_ml: number;
            /** Format: date-time */
            occurred_at?: string | null;
            /**
             * @default custom
             * @enum {string}
             */
            source: "quick_add" | "custom";
            note?: string | null;
        };
        WaterDay: {
            /** Format: date */
            local_date: string;
            total_ml: number;
            goal_ml: number;
            progress_ratio: number;
            entries: {
                id: string;
                amount_ml: number;
                /** Format: date-time */
                occurred_at: string;
            }[];
        };
        GrowthSuggestion: {
            exercise_id: string;
            exercise_name: string;
            /** @enum {string} */
            suggestion_type: "insufficient_data" | "increase_load" | "add_rep" | "repeat_load" | "maintain" | "reduce_volume" | "easier_variation" | "no_progression";
            suggested_delta?: number | null;
            delta_unit?: string | null;
            /** @enum {string} */
            confidence: "insufficient" | "low" | "medium" | "high";
            explanation: string[];
            source_session_ids: string[];
        };
        PublicDashboard: {
            /** Format: date */
            date: string;
            profile: components["schemas"]["PublicProfile"];
            scheduled_day?: components["schemas"]["SplitDay"] | null;
            active_session?: components["schemas"]["WorkoutSession"] | null;
            muscle_targets: components["schemas"]["MuscleTarget"][];
            water?: components["schemas"]["WaterDay"] | null;
            latest_achievements: components["schemas"]["Achievement"][];
        };
    };
    responses: {
        /** @description Invalid request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication required or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limited. */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        LocalDate: string;
        ExerciseId: string;
        SplitId: string;
        SessionId: string;
        SetId: string;
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy service. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getPublicDashboard: {
        parameters: {
            query?: {
                date?: components["parameters"]["LocalDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public dashboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicDashboard"];
                };
            };
        };
    };
    getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicProfile"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Owner profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProfile"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfileUpdate"];
            };
        };
        responses: {
            /** @description Updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Updated settings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listExercises: {
        parameters: {
            query?: {
                q?: string;
                primary_muscle?: string;
                secondary_muscle?: string;
                body_region?: string;
                movement_pattern?: string;
                equipment?: string;
                unilateral?: boolean;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"][];
                };
            };
        };
    };
    createExercise: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseWrite"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Exercise. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                exercise_id: components["parameters"]["ExerciseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseWrite"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Exercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listSplits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Splits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"][];
                };
            };
        };
    };
    createSplit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitWrite"];
            };
        };
        responses: {
            /** @description Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Split. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SplitWrite"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    activateSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                split_id: components["parameters"]["SplitId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activated split. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Split"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                exercise_id?: string;
                public_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions, filtered by visibility. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"][];
                };
            };
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSession"];
            };
        };
        responses: {
            /** @description Started session. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session, filtered by visibility. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionUpdate"];
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    addOrSubstituteSessionExercise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddSessionExercise"];
            };
        };
        responses: {
            /** @description Added/substituted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionExercise"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createSet: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWrite"];
            };
        };
        responses: {
            /** @description Set and record result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetWriteResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted and records rebuilt. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateSet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: components["parameters"]["SetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetWrite"];
            };
        };
        responses: {
            /** @description Updated set and affected records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetWriteResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    completeSession: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path: {
                session_id: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Completed session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutSession"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWaterToday: {
        parameters: {
            query?: {
                date?: components["parameters"]["LocalDate"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible daily hydration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterDay"];
                };
            };
        };
    };
    addWater: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WaterWrite"];
            };
        };
        responses: {
            /** @description Added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterDay"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    undoWater: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest entry removed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaterDay"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRecords: {
        parameters: {
            query?: {
                exercise_id?: string;
                current_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visible records. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonalRecord"][];
                };
            };
        };
    };
    getGrowthSuggestions: {
        parameters: {
            query?: {
                date?: components["parameters"]["LocalDate"];
                split_day_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Explainable suggestions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthSuggestion"][];
                };
            };
        };
    };
    exportData: {
        parameters: {
            query: {
                format: "json" | "csv";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Export. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
